export * from './login/login.component'
export * from './dashboard/dashboard.component'
export * from './header/header.component'
export * from './event-list/event-list.component'
export * from './prediction-list/prediction-list.component'
export * from './user-points/user-points.component'
export * from './global-prediction/global-prediction.component'
export * from './leaderboards/leaderboards.component'
